# Helm chart values used for development

# -- Warren - app service --
app:
  enabled: true
  django:
    allowedHosts:
      - "localhost"
    configuration: "Development"
  image:
    pullPolicy: Always
  persistence:
    enabled: true

# -- Warren - api service --
api:
  enabled: true
  fastapi:
    allowedHosts: 
    - "http://localhost:8080"
  image:
    pullPolicy: Always

# -- Warren - postgresql service --
postgresql:
  enabled: true
  image:
    tag: 12.17.0-debian-11-r12
  auth:
    username: fun
    password: pass
    database: warren-api
  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE "warren-app";
          GRANT ALL PRIVILEGES ON DATABASE "warren-app" TO fun;
