version: '3.8'

services:
  postgresql:
    image: postgres:12
    env_file:
      - .env

  app:
    build:
      context: src/app
      target: "${WARREN_APP_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${WARREN_APP_IMAGE_NAME:-warren}:${WARREN_APP_IMAGE_TAG:-app-development}"
    environment:
      PYLINTHOME: /app/.pylint.d
    env_file:
      - .env
    ports:
      - "${WARREN_APP_SERVER_PORT:-8090}:${WARREN_APP_SERVER_PORT:-8090}"
    volumes:
      - ./src/app:/app
    depends_on:
      - postgresql
      - api
      - frontend

  api:
    build:
      context: src/api
      target: "${WARREN_API_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${WARREN_API_IMAGE_NAME:-warren}:${WARREN_API_IMAGE_TAG:-api-development}"
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    ports:
      - "${WARREN_API_SERVER_PORT:-8100}:${WARREN_API_SERVER_PORT:-8100}"
    command:
      - uvicorn
      - "core.warren.api:app"
      - "--proxy-headers"
      - "--log-config"
      - "core/logging-config.dev.yaml"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${WARREN_API_SERVER_PORT:-8100}"
      - "--reload"
    volumes:
      - ./src/api:/app
      - ./bin/patch_statements_date.py:/opt/src/patch_statements_date.py
      - ./bin/seed_experience_index.py:/opt/src/seed_experience_index.py
    depends_on:
      - ralph
      - postgresql

  frontend:
    build:
      context: src/frontend
      target: "${WARREN_FRONTEND_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${WARREN_FRONTEND_IMAGE_NAME:-warren}:${WARREN_FRONTEND_IMAGE_TAG:-frontend-development}"
    environment:
      HOME: /tmp
    command:
      - yarn
      - run
      - dev
    volumes:
      - ./src/frontend:/app
      - .git:/app/.git
      - ./src/app/staticfiles:/app/staticfiles
    depends_on:
      - api

  # -- backends
  ralph:
    image: fundocker/ralph:3.8.0
    user: ${DOCKER_USER:-1000}
    env_file:
      - .env
    ports:
      - "${RALPH_RUNSERVER_PORT:-8200}:${RALPH_RUNSERVER_PORT:-8200}"
    command:
      - ralph
      - "-v"
      - DEBUG
      - runserver
      - "-b"
      - "es"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 2g

  # -- tools
  dockerize:
    image: jwilder/dockerize
    volumes:
      - ./src/app/staticfiles:/app/staticfiles

  notebook:
    build:
      context: ./notebook
    user: "root:root"
    environment:
      NB_UID: ${DOCKER_UID:-1000}
      NB_GID: ${DOCKER_GID:-1000}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    ports:
      - 8888:8888
    group_add:
      - users
    volumes:
      - ./notebook/notebooks:/home/jovyan/work
      - ./src/api:/home/jovyan/work/warren
      - ./data:/home/jovyan/work/data

  docs:
    build:
      context: ./docs
      args:
        DOCKER_GID: ${DOCKER_GID:-1000}
        DOCKER_UID: ${DOCKER_UID:-1000}
    user: ${DOCKER_USER:-1000}
    environment:
      HOME: /home/docs
    command:
      - mkdocs
      - serve
      - "--dev-addr"
      - "0.0.0.0:8000"
    ports:
      - "${WARREN_DOCS_SERVER_PORT:-8000}:${WARREN_DOCS_SERVER_PORT:-8000}"
    volumes:
      - .:/app
      - ~/.gitconfig:/home/docs/.gitconfig
      - ~/.ssh:/home/docs/.ssh

  mike:
    image: warren-docs
    user: ${DOCKER_USER:-1000}
    environment:
      HOME: /home/docs
    command:
      - mike
      - serve
      - "--dev-addr"
      - "0.0.0.0:8001"
    ports:
      - "${WARREN_DOCS_MIKE_PORT:-8001}:${WARREN_DOCS_MIKE_PORT:-8001}"
    volumes:
      - .:/app
      - ~/.gitconfig:/home/docs/.gitconfig
      - ~/.ssh:/home/docs/.ssh
