version: '3.4'

services:
  backend:
    build:
      context: src/backend
      target: "${WARREN_BACKEND_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${WARREN_BACKEND_IMAGE_NAME:-warren-backend}:${WARREN_BACKEND_IMAGE_TAG:-development}"
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    ports:
      - "${WARREN_BACKEND_SERVER_PORT:-8100}:${WARREN_BACKEND_SERVER_PORT:-8100}"
    command:
      - uvicorn
      - "warren.api:app"
      - "--proxy-headers"
      - "--log-config"
      - "core/logging-config.yaml"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${WARREN_BACKEND_SERVER_PORT:-8100}"
      - "--reload"
    volumes:
      - ./src/backend:/app
      - ./bin/patch_statements_date.py:/opt/src/patch_statements_date.py
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: src/frontend
      target: "${WARREN_FRONTEND_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${WARREN_FRONTEND_IMAGE_NAME:-warren-frontend}:${WARREN_FRONTEND_IMAGE_TAG:-development}"
    environment:
      HOME: /tmp
    ports:
      - "${WARREN_FRONTEND_SERVER_PORT:-3000}:${WARREN_FRONTEND_SERVER_PORT:-3000}"
      - "${WARREN_FRONTEND_DOCS_PORT:-3001}:${WARREN_FRONTEND_DOCS_PORT:-3001}"
    command:
      - yarn
      - run
      - dev
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend

  # -- backends
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 2g

  # -- tools
  ralph:
    image: fundocker/ralph

  dockerize:
    image: jwilder/dockerize
