---
apiVersion: v1
kind: Secret
metadata:
  name: warren-app-db
type: Opaque
stringData:
  WARREN_APP_DB_PASSWORD: pass
---
apiVersion: v1
kind: Secret
metadata:
  name: warren-app-secret-key
type: Opaque
stringData:
  WARREN_APP_SECRET_KEY: change_me_please
---
apiVersion: v1
kind: Secret
metadata:
  name: warren-signing-key
type: Opaque
stringData:
  WARREN_APP_SIGNING_KEY: change_me
---