apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "api.fullname" . }}-logging-config"
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  {{ with .Values.loggingConfig }}
  logging-config.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
