apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.jobs.dbMigrate.name }}"
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: "warren-api-env"
            - configMapRef:
                name: "warren-api-database"
            - secretRef:
                name: {{ .Values.lrs.passwordSecretName | quote }}
            - secretRef:
                name: {{ .Values.database.passwordSecretName | quote }}
            - secretRef:
                name: {{ .Values.signing.keySecretName | quote }}
          {{ with .Values.jobs.dbMigrate.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .Values.jobs.dbMigrate.restartPolicy }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
