"""update cache schema

Revision ID: 2aaa9e8fc591
Revises: ecc3caa6bbbd
Create Date: 2023-09-07 15:40:04.677683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2aaa9e8fc591"
down_revision: Union[str, None] = "ecc3caa6bbbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cache", sa.Column("since", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cache", sa.Column("until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cache", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cache", "created_at")
    op.drop_column("cache", "until")
    op.drop_column("cache", "since")
    # ### end Alembic commands ###
