apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.fullname" . }}-nginx"
data:
  config: |
    events {
      worker_connections 1024; # increase if you have lots of clients
      accept_mutex off; # set to 'on' if nginx worker_processes > 1
      # 'use epoll;' to enable for Linux 2.6+
      # 'use kqueue;' to enable for FreeBSD, OSX
    }

    http {
        upstream django_app {
            server localhost:{{ .Values.django.port }};
        }

        server {
            listen {{ .Values.nginx.port }};

            root /usr/share/nginx;
            location / {
              # checks for static file, if not found proxy to app
              try_files $uri @proxy_to_app;
            }

            location @proxy_to_app {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_redirect off;
                proxy_pass http://django_app;
            }
        }

        server {
          listen 5000;
          server_name localhost;

          location /__status__ {
            stub_status;
            access_log off;
          }

        }

        include /etc/nginx/mime.types;
    }
