apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- include "django.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: "{{ .Chart.Name }}-collectstatic"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "python"
            - "manage.py"
            - "collectstatic"
            - "--no-input"
          env:
            {{- include "app.envs" . | nindent 12 }}
          volumeMounts:
            - name: "static"
              mountPath: /app/static
      containers:
        - name: "{{ .Chart.Name }}-django"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /__heartbeat__
              port: {{ .Values.django.port }}
              httpHeaders:
                - name: "Host"
                  value: "{{ .Values.ingress.host }}"
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /__lbheartbeat__
              port: {{ .Values.django.port }}
              httpHeaders:
                - name: "Host"
                  value: "{{ .Values.ingress.host }}"
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            exec:
              command:
                - python3
                - manage.py
                - migrate
                - --check
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 30
          env:
            {{- include "app.envs" . | nindent 12 }}
          {{ with .Values.django.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: static
              mountPath: /app/static
            - name: {{ .Values.volumes.media.name }}
              mountPath: {{ .Values.volumes.media.mountPath }}
        - name: "{{ .Chart.Name }}-nginx"
          image: nginx:1.25.4-alpine
          volumeMounts:
            - name: "static"
              mountPath: /usr/share/nginx/static
            - name: {{ .Values.volumes.media.name }}
              mountPath: /usr/share/nginx/media
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /__status__
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: {{ .Values.volumes.media.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.media.claimName }}
        - name: nginx
          configMap:
            items:
              - key: config
                path: nginx.conf
            name: "{{ template "app.fullname" . }}-nginx"
        - name: "static"
          emptyDir:
            sizeLimit: 50Mi
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
