apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__heartbeat__
              port: http
              httpHeaders:
                - name: Host
                  value: "{{ first .Values.allowedHosts }}"
          readinessProbe:
            httpGet:
              path: /__lbheartbeat__
              port: http
              httpHeaders:
                - name: Host
                  value: "{{ first .Values.allowedHosts }}"
          envFrom:
            - configMapRef:
                name: "warren-app-env"
            - configMapRef:
                name: "warren-app-database"
            - secretRef:
                name: {{ .Values.database.passwordSecretName | quote }}
            - secretRef:
                name: {{ .Values.secretKeySecretName | quote }}
            - secretRef:
                name: {{ .Values.signing.keySecretName | quote }}
          {{ with .Values.podCommand }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: {{ .Values.persistence.volumes.media.name }}
              mountPath: {{ .Values.persistence.volumes.media.mountPath }}
            - name: {{ .Values.persistence.volumes.static.name }}
              mountPath: {{ .Values.persistence.volumes.static.mountPath }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: {{ .Values.persistence.volumes.media.name }}
          persistentVolumeClaim:
      {{- if .Values.persistence.volumes.media.claimName }}
            claimName: {{ .Values.volumes.media.claimName }}
      {{- else }}
            claimName: {{ include "app.fullname" . }}-media
      {{- end }}
        - name: {{ .Values.persistence.volumes.static.name }}
          persistentVolumeClaim:
      {{- if .Values.persistence.volumes.static.claimName }}
            claimName: {{ .Values.volumes.static.claimName }}
      {{- else }}
            claimName: {{ include "app.fullname" . }}-static
      {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
