apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.jobs.dbMigrate.name }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
spec:
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.djangoSettingsModule }}
            - name: DJANGO_CONFIGURATION
              value: {{ .Values.djangoConfiguration }}
            - name: WARREN_APP_DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: WARREN_APP_SIGNING_ALGORITHM
              value: {{ .Values.signingAlgorithm }}
            - name: WARREN_APP_ACCESS_TOKEN_LIFETIME
              value: {{ .Values.accessTokenLifetime | quote }}
            - name: WARREN_APP_REFRESH_TOKEN_LIFETIME
              value: {{ .Values.refreshTokenLifetime | quote }}
            - name: WARREN_APP_LTI_ACCESS_TOKEN_LIFETIME
              value: {{ .Values.ltiAccessTokenLifetime | quote }}
            - name: WARREN_APP_ALLOWED_HOSTS
              value: {{ include "app.allowedHosts" . }}
          envFrom:
            - secretRef:
                name: {{ .Values.envVarsSecret | quote }}
          {{ with .Values.jobs.dbMigrate.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .Values.jobs.dbMigrate.restartPolicy }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
