{{- if $.Values.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secretKeySecretName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
data: 
  WARREN_APP_SECRET_KEY: {{ $.Values.secretKey | b64enc }}
{{- end }}