{{- if $.Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.database.passwordSecretName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
data: 
  WARREN_APP_DB_PASSWORD: {{ $.Values.database.password | b64enc }}
{{- end }}